In [1]:
%matplotlib notebook

import pandas as pd
import csv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = "2010-2017-NC-County-Population-Estimates_by_year1.csv"
data = pd.read_csv(path, names=["FIPS Code","State and County Names", "April 1 2010 Estimates Base", "July 1 2010 Estimate", "July 1 2011 Estimate", "July 1 2012 Estimate", "July 1 2013 Estimate", "July 1 2014 Estimate","July 1 2015 Estimate", "July 1 2016 Estimate", "July 1 2017 Estimate", "Total_Change"])
data.head(10)

,FIPS Code,State and County Names,April 1 2010 Estimates Base,July 1 2010 Estimate,July 1 2011 Estimate,July 1 2012 Estimate,July 1 2013 Estimate,July 1 2014 Estimate,July 1 2015 Estimate,July 1 2016 Estimate,July 1 2017 Estimate,Total_Change
0,Population Estimates for NC State and Counties...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Source: U.S. Census Bureau, Population Estimat...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FIPS Code,Geography Name,Total Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,"April 1, 2010 Estimates Base","July 1, 2010 Estimate","July 1, 2011 Estimate","July 1, 2012 Estimate","July 1, 2013 Estimate","July 1, 2014 Estimate","July 1, 2015 Estimate","July 1, 2016 Estimate","July 1, 2017 Estimate",Total Change
5,37000,North Carolina,"9,535,721","9,574,247","9,662,940","9,755,299","9,849,812","9,941,160","10,041,769","10,156,689","10,273,419","737,698"
6,37001,Alamance County,"151,198","151,490","152,857","153,471","154,417","155,698","157,389","159,325","162,391","11,193"
7,37003,Alexander County,"37,192","37,241","37,039","36,940","37,091","37,092","37,058","37,270","37,286",94
8,37005,Alleghany County,"11,154","11,141","11,025","10,956","10,920","10,911","10,869","10,945","11,031",-123
9,37007,Anson County,"26,928","26,851","26,517","26,322","25,975","25,978","25,594","25,119","24,991","-1,937"

In [175]:
test = '  test  '

In [176]:
newTest = test.str.strip()

AttributeError: 'str' object has no attribute 'str'

In [3]:
drop_data = data.dropna()
drop_data.head(15)

,FIPS Code,State and County Names,April 1 2010 Estimates Base,July 1 2010 Estimate,July 1 2011 Estimate,July 1 2012 Estimate,July 1 2013 Estimate,July 1 2014 Estimate,July 1 2015 Estimate,July 1 2016 Estimate,July 1 2017 Estimate,Total_Change
5,37000,North Carolina,"9,535,721","9,574,247","9,662,940","9,755,299","9,849,812","9,941,160","10,041,769","10,156,689","10,273,419","737,698"
6,37001,Alamance County,"151,198","151,490","152,857","153,471","154,417","155,698","157,389","159,325","162,391","11,193"
7,37003,Alexander County,"37,192","37,241","37,039","36,940","37,091","37,092","37,058","37,270","37,286",94
8,37005,Alleghany County,"11,154","11,141","11,025","10,956","10,920","10,911","10,869","10,945","11,031",-123
9,37007,Anson County,"26,928","26,851","26,517","26,322","25,975","25,978","25,594","25,119","24,991","-1,937"
10,37009,Ashe County,"27,238","27,231","27,008","26,957","26,889","26,838","26,727","26,754","26,957",-281
11,37011,Avery County,"17,806","17,761","17,728","17,575","17,604","17,597","17,440","17,500","17,536",-270
12,37013,Beaufort County,"47,763","47,799","47,663","47,436","47,391","47,350","47,389","47,361","47,088",-675
13,37015,Bertie County,"21,280","21,250","20,860","20,502","20,350","20,353","20,188","19,449","19,224","-2,056"
14,37017,Bladen County,"35,182","35,194","34,920","34,866","34,704","34,462","34,211","33,796","33,478","-1,704"
15,37019,Brunswick County,"107,431","108,068","110,237","112,081","114,999","118,384","122,297","126,353","130,897","23,466"
16,37021,Buncombe County,"238,328","238,733","241,224","243,741","246,948","249,302","252,149","255,334","257,607","19,279"
17,37023,Burke County,"90,838","90,577","90,490","89,755","89,141","88,610","88,644","88,802","89,293","-1,545"
18,37025,Cabarrus County,"178,086","178,537","181,228","184,232","187,160","191,662","196,315","201,573","206,872","28,786"
19,37027,Caldwell County,"83,047","83,009","82,446","82,096","82,041","81,681","81,537","81,787","81,981","-1,066"

In [5]:
newCol = []
newCol = drop_data['Total_Change'].str.strip()

In [6]:
newCol.head()

5    737,698
6     11,193
7         94
8       -123
9     -1,937
Name: Total_Change, dtype: object

In [14]:
newCol1 = []
for y in newCol:
    y = y.replace(",", "")
    newCol1.append(int(y))
newCol1

[737698,
 11193,
 94,
 -123,
 -1937,
 -281,
 -270,
 -675,
 -2056,
 -1704,
 23466,
 19279,
 -1545,
 28786,
 -1066,
 601,
 2418,
 -1102,
 3216,
 7993,
 646,
 -688,
 483,
 -696,
 -2171,
 -925,
 13113,
 2784,
 2179,
 2633,
 1235,
 635,
 41656,
 -3798,
 25646,
 5610,
 14065,
 -642,
 -320,
 2035,
 -344,
 38535,
 -3324,
 18057,
 2050,
 9003,
 -765,
 7227,
 -454,
 16249,
 2697,
 27836,
 -569,
 2572,
 -2635,
 4437,
 163,
 815,
 957,
 -1723,
 157187,
 -504,
 -349,
 9018,
 -1838,
 24515,
 -2239,
 16094,
 11258,
 -454,
 -918,
 8760,
 21,
 -102,
 10876,
 38,
 1481,
 -1844,
 -1627,
 -2682,
 2126,
 -1265,
 -39,
 -1064,
 896,
 -1700,
 -1524,
 313,
 869,
 -355,
 30017,
 -1208,
 171144,
 -1141,
 -1202,
 4057,
 1526,
 -727,
 441,
 -635,
 -73]

In [11]:
newCol1.

AttributeError: 'list' object has no attribute 'types'

In [189]:
drop_data["Total_Change"] = drop_data.Total_Change.astype(int)

ValueError: invalid literal for int() with base 10: '737,698'

In [160]:
drop_data.dtypes

FIPS Code                      object
State and County Names         object
April 1 2010 Estimates Base    object
July 1 2010 Estimate           object
July 1 2011 Estimate           object
July 1 2012 Estimate           object
July 1 2013 Estimate           object
July 1 2014 Estimate           object
July 1 2015 Estimate           object
July 1 2016 Estimate           object
July 1 2017 Estimate           object
Total_Change                   object
dtype: object

In [12]:
population_change = drop_data[["State and County Names", "Total Change"]]
population_change = population_change.set_index("State and County Names")
population_change.head()

KeyError: "['Total Change'] not in index"

In [124]:
population_change.plot(kind="bar",figsize=(20,3))
plt.title("Population Change by County from 2010-2017")

plt.show()
plt.tight_layout()

TypeError: Empty 'DataFrame': no numeric data to plot